<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Projeto_POO</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="UI\Images\Games\gta3.jpg" />
    <None Remove="UI\Images\Games\gtasa.jpg" />
    <None Remove="UI\Images\Games\mortalkombatarmageddon.jpg" />
    <None Remove="UI\Images\Games\pes2012.jpg" />
    <None Remove="UI\Images\Games\residentevil4.jpg" />
    <None Remove="UI\Images\Games\SNES\supermarioworld.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Emulators\SNES\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Games\SNES\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="UI\Images\Games\PS2\gta3.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Images\Games\PS2\gtasa.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Images\Games\PS2\mortalkombatarmageddon.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Images\Games\PS2\pes2012.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Images\Games\PS2\residentevil4.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Images\Games\SNES\supermarioworld.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Images\Games\SNES\issdeluxe.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Images\Games\SNES\mk3.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
